"""crypto.py <-> wa_gateway/src/crypto.ts: the two must produce and accept
the same blobs, since the gateway stores Baileys auth state with the same
key, format and AAD convention as every other secret.

(a) Golden vectors committed in wa_gateway/test/golden/crypto_vectors.json
    (generated by crypto.py with a fixed nonce; the Node test checks the
    same file) — always run.
(b) Live round trip through `node dist/cryptotool.js` in both directions —
    skipped when node or the compiled dist is absent.
"""

from __future__ import annotations

import json
import os
import shutil
import subprocess
from pathlib import Path

import pytest

import crypto

APP_DIR = Path(__file__).resolve().parent.parent
GATEWAY_DIR = APP_DIR / "wa_gateway"
VECTORS = json.loads((GATEWAY_DIR / "test" / "golden" / "crypto_vectors.json").read_text(encoding="utf-8"))["vectors"]
CRYPTOTOOL = GATEWAY_DIR / "dist" / "cryptotool.js"


def _use_keyring(monkeypatch, tmp_path, keyring: dict) -> None:
    monkeypatch.delenv("USERBOT_MASTER_KEY", raising=False)
    monkeypatch.delenv("USERBOT_MASTER_KEY_FILE", raising=False)
    if "file" in keyring:
        path = tmp_path / "keys"
        path.write_text(keyring["file"], encoding="utf-8")
        monkeypatch.setenv("USERBOT_MASTER_KEY_FILE", str(path))
    else:
        monkeypatch.setenv("USERBOT_MASTER_KEY", keyring["env"])
    crypto.reset_cache()


@pytest.mark.parametrize("vector", VECTORS, ids=[v["name"] for v in VECTORS])
def test_golden_vectors_hold_for_crypto_py(vector, monkeypatch, tmp_path):
    _use_keyring(monkeypatch, tmp_path, vector["keyring"])
    aad = vector["aad"].encode("utf-8")
    plaintext = bytes.fromhex(vector["plaintext_hex"])
    blob = bytes.fromhex(vector["blob_hex"])
    assert crypto.decrypt(blob, aad=aad) == plaintext
    # Same nonce => byte-identical blob (the fixed-nonce hook the vectors were made with).
    monkeypatch.setattr(crypto.os, "urandom", lambda n: bytes.fromhex(vector["nonce_hex"])[:n])
    assert crypto.encrypt(plaintext, aad=aad) == blob
    assert blob[0] == crypto.BLOB_VERSION and blob[1] == vector["key_id"]
    crypto.reset_cache()


def test_golden_file_is_what_the_node_test_reads():
    text = (GATEWAY_DIR / "test" / "crypto.test.ts").read_text(encoding="utf-8")
    assert "golden/crypto_vectors.json" in text
    assert len(VECTORS) >= 5
    assert {v["aad"] for v in VECTORS} >= {"acct01:auth_key", "wa-demo:wa_auth:pre-key:17"}


# --- live round trip through the compiled gateway ------------------------------


def _node() -> str:
    node = os.environ.get("NODE_BIN") or shutil.which("node")
    if not node:
        pytest.skip("node not found (set NODE_BIN)")
    if not CRYPTOTOOL.exists():
        pytest.skip(f"{CRYPTOTOOL} missing: run `npm run build` in wa_gateway")
    return node


def _cryptotool(node: str, mode: str, aad: str, data: bytes, env: dict) -> bytes:
    result = subprocess.run(
        [node, str(CRYPTOTOOL), mode, aad], input=data.hex(), capture_output=True, text=True, timeout=60,
        env={**os.environ, **env},
    )
    assert result.returncode == 0, result.stderr
    return bytes.fromhex(result.stdout.strip())


@pytest.mark.parametrize("keyring", [
    {"env": "MTIzNDU2Nzg5MDEyMzQ1Njc4OTAxMjM0NTY3ODkwMTI="},
    {"file": json.dumps({"active": 2, "keys": {"1": "MTIzNDU2Nzg5MDEyMzQ1Njc4OTAxMjM0NTY3ODkwMTI=", "2": "MjIyMjIyMjIyMjIyMjIyMjIyMjIyMjIyMjIyMjIyMjI="}})},
], ids=["env", "keyring-file"])
def test_python_encrypts_node_decrypts_and_back(keyring, monkeypatch, tmp_path):
    node = _node()
    _use_keyring(monkeypatch, tmp_path, keyring)
    env = {k: os.environ[k] for k in ("USERBOT_MASTER_KEY", "USERBOT_MASTER_KEY_FILE") if k in os.environ}
    aad = crypto.aad_for("acct-live", "wa_auth:creds:")
    plaintext = b"\x00\x01binary + unicode caf\xc3\xa9" + os.urandom(40)

    from_python = crypto.encrypt(plaintext, aad=aad)
    assert _cryptotool(node, "decrypt", aad.decode(), from_python, env) == plaintext

    from_node = _cryptotool(node, "encrypt", aad.decode(), plaintext, env)
    assert from_node[0] == crypto.BLOB_VERSION
    assert from_node[1] == crypto.load_keyring().active_id
    assert crypto.decrypt(from_node, aad=aad) == plaintext
    assert from_node != from_python  # fresh nonce on each side

    with pytest.raises(crypto.DecryptError):
        crypto.decrypt(from_node, aad=crypto.aad_for("acct-live", "auth_key"))
    result = subprocess.run(
        [node, str(CRYPTOTOOL), "decrypt", "acct-other:wa_auth:creds:"], input=from_python.hex(),
        capture_output=True, text=True, timeout=60, env={**os.environ, **env},
    )
    assert result.returncode != 0 and "authentication failed" in result.stderr
    crypto.reset_cache()
